# Generated by Django 5.0 on 2023-12-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default/default.jpeg', null=True, upload_to='post_images/'),
        ),
    ]
