# Generated by Django 5.0 on 2023-12-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='facebook_link',
            field=models.URLField(blank=True, help_text='can be left blank', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram_lint',
            field=models.URLField(blank=True, help_text='can be left blank', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter_link',
            field=models.URLField(blank=True, help_text='can be left blank', null=True),
        ),
    ]
