# Generated by Django 5.0 on 2023-12-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_alter_contact_facebook_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='instagram_lint',
            new_name='instagram_link',
        ),
    ]
