# Generated by Django 5.0 on 2023-12-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_rename_instagram_lint_contact_instagram_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='can be left blank', null=True),
        ),
    ]
